define(['extends'], {
    splitBytes: function splitBytes(string) {
        return string.match(/\[..]/g).map(function (value) {
            return parseInt(value.slice(1, 3), 16);
        });
    },
    defined: function defined(value) {
        return typeof value === 'undefined' ? null : value;
    },
    codeTable: function codeTable() {
        var result = {};

        for (var i = 0x00; i < 0x80; ++i) {
            result[['[', i.rotl8(2).toHex(2), ']'].join('')] = String.fromCharCode(i);
        }

        return result;
    },
    defaultRulesASCII: {
        "[00][63][68][61][72][00]": ["\n[НАЧАЛО_РЕПЛИКИ]\n", true],     // [00]char[00]
        "[25][4B]": ["\n[КОНЕЦ_РЕПЛИКИ]\n", true],                      // %K
        "[5C][6E]": ["[ПЕРЕНОС]\n", true],                              // \n
        //"[00]": ["[NUL]", true],
        //"[01]": ["[SOH]", true],
        //"[02]": ["[STX]", true],
        //"[03]": ["[ETX]", true],
        //"[04]": ["[EOT]", true],
        //"[05]": ["[ENQ]", true],
        //"[06]": ["[ACK]", true],
        //"[07]": ["[BEL]", true],
        //"[08]": ["[BS]", true],
        //"[09]": ["[HT]", true],
        //"[0A]": ["[LF]", true],
        //"[0B]": ["[VT]", true],
        //"[0C]": ["[FF]", true],
        //"[0D]": ["[CR]", true],
        //"[0E]": ["[SO]", true],
        //"[0F]": ["[SI]", true],
        //"[10]": ["[DLE]", true],
        //"[11]": ["[DC1]", true],
        //"[12]": ["[DC2]", true],
        //"[13]": ["[DC3]", true],
        //"[14]": ["[DC4]", true],
        //"[15]": ["[NAK]", true],
        //"[16]": ["[SYN]", true],
        //"[17]": ["[ETB]", true],
        //"[18]": ["[CAN]", true],
        //"[19]": ["[EM]", true],
        //"[1A]": ["[SUB]", true],
        //"[1B]": ["[ESC]", true],
        //"[1C]": ["[FS]", true],
        //"[1D]": ["[GS]", true],
        //"[1E]": ["[RS]", true],
        //"[1F]": ["[US]", true],
        "[20]": [" ", true],
        "[21]": ["!", true],
        "[22]": ["\"", true],
        "[23]": ["#", true],
        "[24]": ["$", true],
        "[25]": ["%", true],
        "[26]": ["&", true],
        "[27]": ["'", true],
        "[28]": ["(", true],
        "[29]": [")", true],
        "[2A]": ["*", true],
        "[2B]": ["+", true],
        "[2C]": [",", true],
        "[2D]": ["-", true],
        "[2E]": [".", true],
        "[2F]": ["/", true],
        "[30]": ["0", true],
        "[31]": ["1", true],
        "[32]": ["2", true],
        "[33]": ["3", true],
        "[34]": ["4", true],
        "[35]": ["5", true],
        "[36]": ["6", true],
        "[37]": ["7", true],
        "[38]": ["8", true],
        "[39]": ["9", true],
        "[3A]": [":", true],
        "[3B]": [";", true],
        "[3C]": ["<", true],
        "[3D]": ["=", true],
        "[3E]": [">", true],
        "[3F]": ["?", true],
        "[40]": ["@", true],
        "[41]": ["A", true],
        "[42]": ["B", true],
        "[43]": ["C", true],
        "[44]": ["D", true],
        "[45]": ["E", true],
        "[46]": ["F", true],
        "[47]": ["G", true],
        "[48]": ["H", true],
        "[49]": ["I", true],
        "[4A]": ["J", true],
        "[4B]": ["K", true],
        "[4C]": ["L", true],
        "[4D]": ["M", true],
        "[4E]": ["N", true],
        "[4F]": ["O", true],
        "[50]": ["P", true],
        "[51]": ["Q", true],
        "[52]": ["R", true],
        "[53]": ["S", true],
        "[54]": ["T", true],
        "[55]": ["U", true],
        "[56]": ["V", true],
        "[57]": ["W", true],
        "[58]": ["X", true],
        "[59]": ["Y", true],
        "[5A]": ["Z", true],
        "[5B]": ["[", true],
        "[5C]": ["\\", true],
        "[5D]": ["]", true],
        "[5E]": ["^", true],
        "[5F]": ["_", true],
        "[60]": ["`", true],
        "[61]": ["a", true],
        "[62]": ["b", true],
        "[63]": ["c", true],
        "[64]": ["d", true],
        "[65]": ["e", true],
        "[66]": ["f", true],
        "[67]": ["g", true],
        "[68]": ["h", true],
        "[69]": ["i", true],
        "[6A]": ["j", true],
        "[6B]": ["k", true],
        "[6C]": ["l", true],
        "[6D]": ["m", true],
        "[6E]": ["n", true],
        "[6F]": ["o", true],
        "[70]": ["p", true],
        "[71]": ["q", true],
        "[72]": ["r", true],
        "[73]": ["s", true],
        "[74]": ["t", true],
        "[75]": ["u", true],
        "[76]": ["v", true],
        "[77]": ["w", true],
        "[78]": ["x", true],
        "[79]": ["y", true],
        "[7A]": ["z", true],
        "[7B]": ["{", true],
        "[7C]": ["|", true],
        "[7D]": ["}", true],
        "[7E]": ["~", true]
        //"[7F]": ["[DEL]", true]
    }
});
